BEGIN;

CREATE TABLE IF NOT EXISTS integracion_novedad (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origen VARCHAR(30) NOT NULL,
    destino VARCHAR(30) NOT NULL,
    entidad VARCHAR(50) NOT NULL,
    entidad_id VARCHAR(200) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    finalizada BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_procesado TIMESTAMPTZ,
    intentos INTEGER NOT NULL DEFAULT 0,
    ultimo_error TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    correlation_id UUID NOT NULL DEFAULT gen_random_uuid(),
    CONSTRAINT integracion_novedad_correlation_id_key UNIQUE (correlation_id),
    CONSTRAINT integracion_novedad_tipo_check
        CHECK (tipo IN ('ALTA', 'MODIFICACION', 'BAJA')),
    CONSTRAINT integracion_novedad_estado_check
        CHECK (estado IN ('PENDIENTE', 'PARCIAL', 'PROCESANDO', 'PROCESADA', 'ERROR')),
    CONSTRAINT integracion_novedad_finalizacion_check
        CHECK (
            (NOT finalizada AND estado IN ('PENDIENTE', 'PARCIAL', 'PROCESANDO', 'ERROR'))
            OR (finalizada AND estado = 'PROCESADA')
        ),
    CONSTRAINT integracion_novedad_intentos_check CHECK (intentos >= 0),
    CONSTRAINT integracion_novedad_version_check CHECK (version >= 1)
);

-- Una entidad puede tener muchas novedades históricas, pero una sola abierta.
CREATE UNIQUE INDEX IF NOT EXISTS integracion_novedad_abierta_idx
    ON integracion_novedad (origen, destino, entidad, entidad_id)
    WHERE NOT finalizada;

CREATE INDEX IF NOT EXISTS integracion_novedad_destino_estado_fecha_idx
    ON integracion_novedad (destino, estado, fecha_creacion);

CREATE TABLE IF NOT EXISTS integracion_novedad_detalle (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    integracion_novedad_id INTEGER NOT NULL
        REFERENCES integracion_novedad(id) ON DELETE CASCADE,
    campo VARCHAR(100) NOT NULL,
    campo_label VARCHAR(150) NOT NULL,
    tipo_dato VARCHAR(30) NOT NULL,
    valor_anterior_json JSONB,
    valor_nuevo_json JSONB,
    estado_revision VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    estado_aplicacion VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    fecha_revision TIMESTAMPTZ,
    revisado_por VARCHAR(100),
    fecha_aplicacion TIMESTAMPTZ,
    ultimo_error TEXT,
    CONSTRAINT integracion_novedad_detalle_campo_key
        UNIQUE (integracion_novedad_id, campo),
    CONSTRAINT integracion_novedad_detalle_revision_check
        CHECK (estado_revision IN ('PENDIENTE', 'ACEPTADO', 'RECHAZADO')),
    CONSTRAINT integracion_novedad_detalle_aplicacion_check
        CHECK (estado_aplicacion IN ('PENDIENTE', 'APLICADO', 'ERROR', 'NO_APLICA'))
);

CREATE INDEX IF NOT EXISTS integracion_novedad_detalle_revision_idx
    ON integracion_novedad_detalle
    (integracion_novedad_id, estado_revision, estado_aplicacion);

-- No se crean políticas públicas: los procesos backend acceden como owner o
-- service role, mientras que anon/authenticated no reciben acceso por RLS.
ALTER TABLE integracion_novedad ENABLE ROW LEVEL SECURITY;
ALTER TABLE integracion_novedad_detalle ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE integracion_novedad IS
    'Bandeja de novedades nacidas en la web para otros sistemas del ecosistema Maxes.';
COMMENT ON COLUMN integracion_novedad.finalizada IS
    'Marca técnica usada para garantizar una sola novedad abierta por entidad.';
COMMENT ON COLUMN integracion_novedad_detalle.valor_anterior_json IS
    'Primer valor conocido antes de los cambios sucesivos aún no procesados.';
COMMENT ON COLUMN integracion_novedad_detalle.valor_nuevo_json IS
    'Último valor conocido, reemplazado mientras la novedad permanezca abierta.';

COMMIT;
