CREATE TABLE IF NOT EXISTS analytics_sesion (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_analytics_session VARCHAR(100) NOT NULL UNIQUE,
    id_analytics_visitor VARCHAR(100) NOT NULL,
    carrito_analytics_id INTEGER NOT NULL
        REFERENCES analytics_carrito(id) ON DELETE CASCADE,
    fecha_hora_inicio TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_hora_ultima_actividad TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    segundos_navegacion_activa INTEGER NOT NULL DEFAULT 0,
    etapa VARCHAR(30) NOT NULL DEFAULT 'catalogo',
    pedido_generado BOOLEAN NOT NULL DEFAULT FALSE,
    tipo_dispositivo VARCHAR(30) NOT NULL DEFAULT 'desconocido',
    sistema_operativo VARCHAR(50) NOT NULL DEFAULT 'otro',
    navegador VARCHAR(50) NOT NULL DEFAULT 'otro',
    origen_campania VARCHAR(100),
    medio_campania VARCHAR(100),
    nombre_campania VARCHAR(150),
    contenido_campania VARCHAR(150),
    termino_campania VARCHAR(150),
    id_click_google VARCHAR(200),
    id_click_meta VARCHAR(200),
    pagina_ingreso VARCHAR(500),
    sitio_origen VARCHAR(500),
    CONSTRAINT analytics_sesion_etapa_check
        CHECK (etapa IN ('catalogo', 'formulario_pedido', 'pedido_generado'))
);

ALTER TABLE analytics_favorito_evento
    ADD COLUMN IF NOT EXISTS id_analytics_session VARCHAR(100);
ALTER TABLE analytics_favorito_evento
    ADD COLUMN IF NOT EXISTS id_evento VARCHAR(100);
ALTER TABLE analytics_articulo_compartido
    ADD COLUMN IF NOT EXISTS id_analytics_session VARCHAR(100);
ALTER TABLE analytics_articulo_compartido
    ADD COLUMN IF NOT EXISTS id_evento VARCHAR(100);
ALTER TABLE analytics_carrito
    ADD COLUMN IF NOT EXISTS segundos_activos_catalogo INTEGER;
ALTER TABLE analytics_carrito
    ADD COLUMN IF NOT EXISTS segundos_activos_pedido INTEGER;
ALTER TABLE analytics_sesion
    ADD COLUMN IF NOT EXISTS segundos_activos_catalogo INTEGER;
ALTER TABLE analytics_sesion
    ADD COLUMN IF NOT EXISTS segundos_activos_pedido INTEGER;

-- Recuperación histórica segura: si la sesión nunca salió del catálogo, todo
-- su tiempo activo registrado pertenece a esa sección. Las sesiones que sí
-- llegaron al formulario no se reparten porque no puede reconstruirse el corte.
UPDATE analytics_sesion
SET segundos_activos_catalogo = segundos_navegacion_activa
WHERE segundos_activos_catalogo IS NULL
  AND etapa = 'catalogo';
CREATE UNIQUE INDEX IF NOT EXISTS analytics_favorito_evento_id_evento_idx
    ON analytics_favorito_evento(id_evento);
CREATE UNIQUE INDEX IF NOT EXISTS analytics_compartido_id_evento_idx
    ON analytics_articulo_compartido(id_evento);

CREATE INDEX IF NOT EXISTS analytics_sesion_fecha_inicio_idx
    ON analytics_sesion (fecha_hora_inicio);
CREATE INDEX IF NOT EXISTS analytics_sesion_visitante_fecha_idx
    ON analytics_sesion (id_analytics_visitor, fecha_hora_inicio);
CREATE INDEX IF NOT EXISTS analytics_sesion_carrito_idx
    ON analytics_sesion (carrito_analytics_id);

-- Conserva la serie histórica: cada registro anterior representaba a la vez
-- una sesión y un carrito. Los nuevos registros separan ambos conceptos.
INSERT INTO analytics_sesion (
    id_analytics_session, id_analytics_visitor, carrito_analytics_id,
    fecha_hora_inicio, fecha_hora_ultima_actividad, segundos_navegacion_activa,
    etapa, pedido_generado, tipo_dispositivo, sistema_operativo, navegador,
    origen_campania, medio_campania, nombre_campania, pagina_ingreso, sitio_origen
)
SELECT
    carrito.id_analytics_session,
    'legacy_' || carrito.id::text,
    carrito.id,
    carrito.fecha_hora_inicio_catalogo,
    carrito.fecha_hora_ultima_actividad,
    carrito.segundos_navegacion_activa,
    CASE
        WHEN carrito.etapa = 'pedido_generado' THEN 'pedido_generado'
        WHEN carrito.etapa = 'formulario_pedido' THEN 'formulario_pedido'
        ELSE 'catalogo'
    END,
    carrito.estado = 'pedido_generado',
    carrito.tipo_dispositivo,
    carrito.sistema_operativo,
    carrito.navegador,
    carrito.origen_campania,
    carrito.medio_campania,
    carrito.nombre_campania,
    carrito.pagina_ingreso,
    carrito.sitio_origen
FROM analytics_carrito AS carrito
ON CONFLICT (id_analytics_session) DO NOTHING;

COMMENT ON TABLE analytics_sesion IS
    'Visitas anonimas de 30 minutos de inactividad; varias sesiones pueden retomar un mismo carrito.';
