DO $$
BEGIN
    IF to_regclass('public.analytics_carrito') IS NULL
       AND to_regclass('public.carrito_analytics') IS NOT NULL THEN
        ALTER TABLE carrito_analytics RENAME TO analytics_carrito;
    END IF;

    IF to_regclass('public.analytics_carrito_detalle') IS NULL
       AND to_regclass('public.carrito_analytics_detalle') IS NOT NULL THEN
        ALTER TABLE carrito_analytics_detalle RENAME TO analytics_carrito_detalle;
    END IF;

    IF to_regclass('public.analytics_favorito_evento') IS NULL
       AND to_regclass('public.favorito_analytics_evento') IS NOT NULL THEN
        ALTER TABLE favorito_analytics_evento RENAME TO analytics_favorito_evento;
    END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS analytics_carrito (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_analytics_session VARCHAR(100) NOT NULL UNIQUE,
    estado VARCHAR(30) NOT NULL DEFAULT 'activo',
    etapa VARCHAR(30) NOT NULL DEFAULT 'carrito',
    fue_abandonado BOOLEAN NOT NULL DEFAULT FALSE,
    cantidad_reactivaciones INTEGER NOT NULL DEFAULT 0,
    tipo_precio VARCHAR(20),
    tipo_dispositivo VARCHAR(30) NOT NULL DEFAULT 'desconocido',
    sistema_operativo VARCHAR(50) NOT NULL DEFAULT 'otro',
    navegador VARCHAR(50) NOT NULL DEFAULT 'otro',
    cantidad_productos INTEGER NOT NULL DEFAULT 0,
    cantidad_unidades INTEGER NOT NULL DEFAULT 0,
    cantidad_favoritos INTEGER NOT NULL DEFAULT 0,
    monto_estimado NUMERIC(18, 2) NOT NULL DEFAULT 0,
    fecha_hora_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_hora_inicio_catalogo TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_hora_ultima_actividad TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_hora_inicio_pedido TIMESTAMPTZ,
    fecha_hora_marcado_abandonado TIMESTAMPTZ,
    fecha_hora_ultima_reactivacion TIMESTAMPTZ,
    fecha_hora_pedido_generado TIMESTAMPTZ,
    segundos_navegacion_activa INTEGER NOT NULL DEFAULT 0,
    pedido_id INTEGER UNIQUE REFERENCES pedido_web(id) ON DELETE SET NULL,
    origen_campania VARCHAR(100),
    medio_campania VARCHAR(100),
    nombre_campania VARCHAR(150),
    pagina_ingreso VARCHAR(500),
    sitio_origen VARCHAR(500),
    CONSTRAINT analytics_carrito_estado_check
        CHECK (estado IN ('activo', 'abandonado', 'pedido_generado')),
    CONSTRAINT analytics_carrito_etapa_check
        CHECK (etapa IN ('carrito', 'formulario_pedido', 'pedido_generado'))
);

CREATE INDEX IF NOT EXISTS analytics_carrito_estado_actividad_idx
    ON analytics_carrito (estado, fecha_hora_ultima_actividad);

CREATE INDEX IF NOT EXISTS analytics_carrito_fue_abandonado_idx
    ON analytics_carrito (fue_abandonado);

CREATE TABLE IF NOT EXISTS analytics_carrito_detalle (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrito_analytics_id INTEGER NOT NULL
        REFERENCES analytics_carrito(id) ON DELETE CASCADE,
    id_incorporacion VARCHAR(100) NOT NULL UNIQUE,
    articulo_id INTEGER NOT NULL REFERENCES articulo_web(id) ON DELETE RESTRICT,
    cantidad_inicial INTEGER NOT NULL,
    cantidad_ultima INTEGER NOT NULL,
    precio_unitario NUMERIC(18, 2) NOT NULL,
    tuvo_comentario BOOLEAN NOT NULL DEFAULT FALSE,
    origen_incorporacion VARCHAR(40) NOT NULL DEFAULT 'catalogo',
    era_favorito_al_agregar BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_hora_agregado TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_hora_ultima_modificacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_hora_eliminado TIMESTAMPTZ,
    CONSTRAINT analytics_carrito_detalle_cantidad_inicial_check
        CHECK (cantidad_inicial > 0),
    CONSTRAINT analytics_carrito_detalle_cantidad_ultima_check
        CHECK (cantidad_ultima > 0)
);

CREATE INDEX IF NOT EXISTS analytics_carrito_detalle_carrito_activo_idx
    ON analytics_carrito_detalle (carrito_analytics_id, fecha_hora_eliminado);

CREATE INDEX IF NOT EXISTS analytics_carrito_detalle_articulo_idx
    ON analytics_carrito_detalle (articulo_id);

CREATE TABLE IF NOT EXISTS analytics_favorito_evento (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrito_analytics_id INTEGER NOT NULL
        REFERENCES analytics_carrito(id) ON DELETE CASCADE,
    articulo_id INTEGER REFERENCES articulo_web(id) ON DELETE SET NULL,
    accion VARCHAR(30) NOT NULL,
    origen VARCHAR(40) NOT NULL,
    cantidad_favoritos INTEGER NOT NULL,
    fecha_hora TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT analytics_favorito_evento_accion_check
        CHECK (accion IN (
            'agregado',
            'quitado',
            'estado_actual',
            'panel_visto',
            'panel_pedido_abierto'
        ))
);

CREATE INDEX IF NOT EXISTS analytics_favorito_evento_accion_origen_idx
    ON analytics_favorito_evento (accion, origen);

CREATE INDEX IF NOT EXISTS analytics_favorito_evento_articulo_idx
    ON analytics_favorito_evento (articulo_id);

ALTER TABLE analytics_carrito
    ADD COLUMN IF NOT EXISTS cantidad_favoritos INTEGER NOT NULL DEFAULT 0;

ALTER TABLE analytics_favorito_evento
    DROP CONSTRAINT IF EXISTS favorito_analytics_evento_accion_check;

ALTER TABLE analytics_favorito_evento
    DROP CONSTRAINT IF EXISTS analytics_favorito_evento_accion_check;

ALTER TABLE analytics_favorito_evento
    ADD CONSTRAINT analytics_favorito_evento_accion_check
    CHECK (accion IN (
        'agregado',
        'quitado',
        'estado_actual',
        'panel_visto',
        'panel_pedido_abierto'
    ));

CREATE TABLE IF NOT EXISTS analytics_articulo_compartido (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrito_analytics_id INTEGER NOT NULL
        REFERENCES analytics_carrito(id) ON DELETE CASCADE,
    articulo_id INTEGER REFERENCES articulo_web(id) ON DELETE SET NULL,
    metodo VARCHAR(40) NOT NULL,
    fecha_hora TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT analytics_articulo_compartido_metodo_check
        CHECK (metodo IN ('whatsapp', 'copiar_link'))
);

ALTER TABLE analytics_articulo_compartido
    DROP CONSTRAINT IF EXISTS analytics_articulo_compartido_metodo_check;

ALTER TABLE analytics_articulo_compartido
    ADD CONSTRAINT analytics_articulo_compartido_metodo_check
    CHECK (metodo IN ('whatsapp', 'copiar_link'));

CREATE INDEX IF NOT EXISTS analytics_articulo_compartido_fecha_idx
    ON analytics_articulo_compartido (fecha_hora);

CREATE INDEX IF NOT EXISTS analytics_articulo_compartido_articulo_idx
    ON analytics_articulo_compartido (articulo_id);

DROP FUNCTION IF EXISTS marcar_carritos_abandonados_analytics();

CREATE OR REPLACE FUNCTION analytics_marcar_carritos_abandonados()
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
    cantidad_marcada INTEGER;
BEGIN
    UPDATE analytics_carrito
    SET
        estado = 'abandonado',
        fue_abandonado = TRUE,
        fecha_hora_marcado_abandonado =
            COALESCE(fecha_hora_marcado_abandonado, CURRENT_TIMESTAMP)
    WHERE estado = 'activo'
      AND cantidad_productos > 0
      AND pedido_id IS NULL
      AND fecha_hora_ultima_actividad <= CURRENT_TIMESTAMP - INTERVAL '12 hours';

    GET DIAGNOSTICS cantidad_marcada = ROW_COUNT;
    RETURN cantidad_marcada;
END;
$$;
